openvpn/init.sls
'service' for 'servcie'. no change to function.
=> typo fix in comment

openvpn/init.sls
Right now for modern salt openvpn service start happens before generation of Diffie–Hellman parameters and will always fail.
This changeset addresses the problem.
Tested with vagrant.
=> Do service start only after everything else.

openvpn/files/server.jinja, pillar.example
The configuration was missing a few key pieces I needed. Instead of simply overriding the file I'm sharing my changes since it may be helpful for others as well.
I have added the following options:
* Auth
* Port-Share (to be able to share a webserver on the same port and provide VPN over 443)
* Deamon
* CCD-Exclusive
* Username-As-Common-Name
* Plugins (e.g. Radius, LDAP)
I also added `{{ source }}` in the template to make it easier to find on which template the generated configuration was based on.
=> Extended the configurable options

openvpn/init.sls, pillar.example
**Summary of Changes**
- Reduce redundancy of configuring server and client separately. 
- Add support for optionally deploying CA cert file.
- Add support for optionally deploying certificate file.
- Add support for optionally deploying private key file.
- Add support for optionally deploying TLA key file.
- Path to cert\keys files is absolute in pillar
=> Add support for optional pillar deployment of certificates & keys.

openvpn/files/server.jinja
e.g. https://www.duosecurity.com/docs/openvpn#configure-the-server
Some plugins expect the extra arguments. When in quotes openvpn fails to start complaining that it can't file the arguments as files.
This may apply to other options too.
=> It's not always useful to have quotes around the plugin option.

openvpn/files/server.jinja
While this settings is discourged in the docs, it's very useful when
configuring OpenVPN for LDAP authentication.
=> Adding client-cert-not-required option to server config

openvpn/config.sls, openvpn/init.sls
On distributions using systemd, the openvpn init service is split in a service for each config file. For example: office.conf and sitetosite.conf will have openvpn@office and openvpn@sitetosite. In this case each service can be handled (start, reboot, stop) independently from each other.
To check if a OS uses systemd I use the grains item "systemd" with the has_value method. Now the service is tied with the config name so I created a new service state in the config.sls file. Last thing was conditioning the requisites (watch_in) for only the new services or the general one in case that systemd is not present.
I've tested the changes in Ubuntu 14.04 and 16.04 and both works. Maybe the implementation could be better but I'm sending the pull request to have the functionality right now.
=> Add support for multiple openvpn services if the OS is using systemd

openvpn/config.sls, openvpn/files/server.jinja, pillar.example
I added support for both creating a crl-verify file and setting the config options to enable it. Includes pillar.example.
=> add crl-verify option and creation of crl-verify file

openvpn/config.sls
Status file should have root username not the user that openvpn is run with.
Ubuntu cannot start openvpn with root permissions
Feb 10 06:58:17 openvpn-us-west-2 ovpn-tcp[9488]: Options error: --status fails with '/etc/openvpn/openvpn-status-tcp.log': Permission denied
After chown root.root - everything works fine.
if i delete that file, openvpn is creating new - owned by root (even if openvpn is started by user nobody)
=> Status file should have root as owner

openvpn/init.sls
Encountered an issue when testing the formula where the package installation failed but the dhparam creation continued. It then failed because openssl couldn't write to the default nonexistent directory `/etc/openvpn/`
=> Creation of DH params should depend on openvpn package installation

openvpn/files/server.jinja
Removing the block that iterates over `_append` in `server.jinja`.
This block is already present in `common_opts.jinja` (https://github.com/saltstack-formulas/openvpn-formula/blob/master/openvpn/files/common_opts.jinja#L211-L216) and doesn't need to appear twice.
If there **_is_** a reason for having this block in both files, then there should be separate `_append` definitions, or some other way to separate these.
=> Removing duplicate config._append block in `server.jinja`

openvpn/config.sls, openvpn/files/common_opts.jinja
Adding support for the `tls-crypt` option enabled after OpenVPN 2.4.0+
Currently the formula does not have this option, even though the formula **_does_** have support for placing a static key with `tls-auth`.
The options `tls-crypt` and `tls-auth` are mutually exclusive, so checks must exist for the presence of the other type: https://forums.openvpn.net/viewtopic.php?t=23076
=> Adding `tls-crypt` support

openvpn/service.sls
dh file creation was running after the service state.
require sls is a great thing.
=> dh file creation should come before service.running

openvpn/files/common_opts.jinja, openvpn/init.sls
Prevent generating Diffie-Hellman parameters unless an openvpn:server block is defined in pillar.
From the man page:
```
--dh file File containing Diffie Hellman parameters in .pem format (required for --tls-server only).
```
=> Create DH parameters on OpenVPN servers only

README.rst, openvpn/gui.sls, pillar.example
Allows setting global config options for the OpenVPN GUI on Windows.
=> Add configuration for Openvpn-GUI (Windows only)

openvpn/config.sls, pillar.example
```mode``` operation of ```file.managed``` is not supported on Windows, and rather than being ignored, it causes states to fail. Therefore ```mode``` cannot be used when running the formula on Windows. Similarly, ```user/group``` are not so useful on Windows.
This PR introduces a macro ```_permissions``` that excludes these parameters when used on Windows.
Follows on from #69.
=> Permissions macro

README.rst, openvpn/adapters.sls, openvpn/files/tap-adapter.ps1
On Windows, TAP-Windows devices need to be managed manually.
This PR ensures a net adapter exists with the name specified using ```dev_node:``` in pillar.
=> Manage TAP-Windows device adapters

openvpn/files/server.jinja
i ran into the following openvpn error message: "Options error: specify only one of --tls-server, --tls-client, or --secret"
=> server: if 'secret' is defined, don't put 'tls-server'

openvpn/config.sls
When using `verify_x509_name: "'C=AT, CN=my.fqdn, L=-, ST=-'"` via `salt-ssh` the resulting config file contained
```
verify-x509-name u"'C=AT
```
This is fixed by encoding the config data structure  in `config.sls` as JSON.
```
% salt --versions-report
Salt Version:
Salt: 2018.3.1
Dependency Versions:
cffi: 1.11.5
cherrypy: Not Installed
dateutil: Not Installed
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: 0.30.1
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: 1.2.5
pycparser: 2.18
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.15 (default, May 27 2018, 00:32:32)
python-gnupg: Not Installed
PyYAML: 3.13 …
```
=> Fix encoding when passing config

openvpn/files/common_opts.jinja
https://www.bleepingcomputer.com/news/security/voracle-attack-can-recover-http-data-from-vpn-connections/
=> Turn off compression by default (VORACLE)

openvpn/files/common_opts.jinja
After #87 there's no way for someone to turn on comp-lzo.
This PR fixes that, keeping back compat in case someone is using comp_lzo: False, and allowing someone to specify the valid options yes, no or adaptive.
If comp_lzo is unconfigured in pillar, then leave it out of the configuration, retaining the default of no compression.
=> Fix flaw in #87 so that comp-lzo can be switched on

README.rst, openvpn/defaults.yaml, openvpn/dhparams.sls, openvpn/files/common_opts.jinja, openvpn/files/server.jinja, openvpn/init.sls, openvpn/install.sls, openvpn/network_manager_networks/files/connection.jinja, openvpn/network_manager_networks/init.sls, openvpn/osmap.yaml, openvpn/repo.sls, openvpn/service.sls, pillar.example
- made list of supported OS distribution versions more maintainable
- split `init.sls` into re-usable sub-states
- implemented management of NetworkManager OpenVPN networks
- made options `daemon` and `port` usable by clients too
Tested on
- FreeBSD 11.2-RELEASE-p4
- Ubuntu 18.04.1 LTS
- Debian GNU/Linux 9.5 (stretch)
- Ubuntu 16.04.5 LTS
=> NetworkManager support

openvpn/config.sls, openvpn/general_config.sls, openvpn/osfamilymap.yaml, pillar.example
I was wondering why my `client-config-dir` option had no effect. Turns out OpenVPN is already non-privileged when it accesses this directory. That led to a rat's tail of smaller changes. :-)
- Config is now owned by `root`. (There's no reason for it to be editable by the OpenVPN process.)
- Config is now only readable by the OpenVPN process' group. (To prevent other local users from leaking information.)
- `/etc/openvpn` is now managed.
- If the user is not `nobody`, it gets managed. (Opt-out via `manage_user: False`)
- If the group is neither `nobody` nor `nogroup`, it gets managed. (Opt-out via `manage_group: False`)
[edit]
Tested on
- Debian 9.5
- FreeBSD 11.2. 
[/edit]
=> Fixed file permissions; manage (non-default) user & group

openvpn/network_manager_networks/files/connection.jinja
Merges the Pillar data of `openvpn:client:${instance_name}` and `openvpn:network_manager:networks:${network_name}:vpn`.
As a result one can override config for each individual NetworkManager OpenVPN connection.
Tested on Ubuntu 16.04.5.
=> NetworkManager: merge Pillar data

openvpn/network_manager_networks/files/connection.jinja
Tested on Ubuntu 18.04 with OpenVPN 2.4.6.
=> network_manager_networks: support OpenVPN's 'proto: tcp-client'

openvpn/files/common_opts.jinja
I've got a case where the TA key is generated independently of the formula, but `tls-auth` shall be set nonetheless.
This patch decouples `ta_content` and `tls_auth`/`tls_crypt`.
Tested on Ubuntu 18.04 and FreeBSD 11.2.
=> fix(config): set tls-auth and tls-crypt independently of ta_content

openvpn/general_config.sls
Tested on FreeBSD 11.2 with Salt 2019.2.0.
Without `if_tap` loaded OpenVPN can't bring up tun/tap devices.
=> fix(freebsd): load if_tap module

openvpn/network_manager_networks/files/connection.jinja, openvpn/network_manager_networks/init.sls
* reduced `pillar.get` calls
* port numbers defined in openvpn:network_manager:networks were ignored. fixed that
Tested on FreeBSD 11.2 and Debian 10.
=> Fix network manager

.travis.yml, .yamllint, openvpn/defaults.yaml, openvpn/osfamilymap.yaml, openvpn/osfingermap.yaml, openvpn/osmap.yaml, pillar.example, test/integration/default/inspec.yml, test/integration/repositories/pillars.sls
* Semi-automated using `ssf-formula` (v0.5.0)
* Fix errors shown below:
```bash
openvpn-formula$ $(grep "\- yamllint" .travis.yml | sed -e "s:^\s\+-\s\(.*\):\1:")
./openvpn/osfamilymap.yaml
1:1       warning  missing document start "---"  (document-start)
15:19     warning  truthy value should be one of [false, true]  (truthy)
17:16     warning  truthy value should be one of [false, true]  (truthy)
18:17     warning  truthy value should be one of [false, true]  (truthy)
./openvpn/defaults.yaml
1:1       warning  missing document start "---"  (document-start)
5:13      warning  truthy value should be one of [false, true]  (truthy)
6:26      warning  truthy value should be one of [false, true]  (truthy)
12:19     warning  truthy value should be one of [false, true]  (truthy) …
```
=> feat(yamllint): include for this repo and apply rules throughout

openvpn/config.sls, openvpn/dhparams.sls, openvpn/osfamilymap.yaml, openvpn/osmap.yaml, openvpn/service.sls, test/integration/default/controls/config_spec.rb, test/integration/default/controls/services_spec.rb, test/integration/repositories/pillars.sls
Based on the work of @mortn (#101) and @n-rodriguez (#102).
The idea is to make the distinction between server and client services an opt-in in the `map.jinja` files.
Debian now properly supports this too.
Tested on FreeBSD 11.2 and Debian 10.
=> fix(config): Debian/Ubuntu distinguishes between service and client

.rubocop.yml, .travis.yml, .yamllint, Gemfile, docs/README.rst, kitchen.vagrant.yml, openvpn/defaults.yaml, openvpn/dhparams.sls, openvpn/init.sls, openvpn/osfamilymap.yaml, test/integration/default/controls/config_spec.rb, test/integration/default/controls/packages_spec.rb, test/integration/default/controls/services_spec.rb, test/integration/default/inspec.yml, test/salt/pillar/default.sls
I'm putting this out there to gather some opinions.
Would this be useful to add to the formula, despite the fact that the tests can't be run in any CI/CD service that I know of?
Testing requires Virtualbox and Vagrant on the local machine.
The OpenVPN server is first run on a linux box, and the tests are subsequently run on the Windows box.
```
KITCHEN_YAML=kitchen.windows.yml kitchen converge default-ubuntu
KITCHEN_YAML=kitchen.windows.yml kitchen verify default-windows
```
=> Windows testing using kitchen-vagrant

openvpn/files/client.jinja, pillar.example
* This option can be enabled on OpenVPN clients, to silence warnings like:
```
openvpn[12345]: WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
```
---
No.
This enables adding a `auto-nocache` line in OpenVPN client config files.  The pillar name is `auth_nocache`, similar to other `auth_` related settings.
=> feat(auth_nocache): support for auth-nocache

Gemfile, Gemfile.lock
---
No.
Pin `chef-utils` to `16.6.14` to work on Ruby 2.5 which is the Ruby version of the Windows image
of GitHub Actions.
The Windows tests in GitHub Actions had started to fail due to Ruby dependency conflicts.
=> chore(gemfile+lock): pin `chef-utils` to `16.6.14` to work on Ruby 2.5

.github/workflows/kitchen.vagrant.yml, .github/workflows/kitchen.windows.yml, kitchen.vagrant.yml, kitchen.windows.yml, test/integration/default/files/_mapdata/windows-2016-server.yaml
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/304
Update the Windows testing to be managed by the `ssf-formula` as well as introduce testing on the Windows Vagrant box.
Included (but commented out) FreeBSD since it's a low-hanging fruit -- after a minor `file.directory` adjustment, only one state is failing (the service won't start up).  Perhaps someone with FreeBSD experience can help get it fixed eventually (CC: @alxwr @sticky-note).  This PR can be merged without waiting for this.
=> ci: enable Vagrant-based testing using GitHub Actions
