saltstack-formulas/openvpn-formula

openvpn/map.jinja

Resubmitting, spent to much time unsuccessfully trying to rebase

Add support for Amazon Linux

---

openvpn/files/client.jinja
openvpn/files/server.jinja

Support the option reneg-sec i.e. Renegotiate data channel key after n seconds

Add support for reneg-sec option.

---

README.rst

Didn't see the readme comment in previous PR, so fixed it in this one :)

Fix README - can now deploy keys\certs.

---

openvpn/files/server.jinja

This commit lets you specify tun-mtu parameter in server configuration

Add tun-mtu support

---

openvpn/init.sls

On my Debian 8 system, the log and sttus files are not created automatically by OpenVPN, and the service errors out. With this pull the files are ensured to exist and be writeable by the OpenVPN daemon.

Esnure log and status files exist.

---

openvpn/init.sls
pillar.example

Added management via pillar of individual client configurations from the server.

Client config management

---

openvpn/files/server.jinja

This closes Issue #28  with the proposed solution.

Fix server default values with server_bridge

---

openvpn/files/client.jinja
openvpn/files/server.jinja

add tls-cipher support

---

openvpn/config.sls
openvpn/files/server.jinja
pillar.example

https://openvpn.net/index.php/open-source/documentation/miscellaneous/78-static-key-mini-howto.html

Add support for simple shared secret configs for site to site

---

openvpn/files/client.jinja
pillar.example

Implement up, down, up-restart, up-delay, and down-pre options used to
execute scripts before and after tunnel creation.

Implement up/down options

---

openvpn/files/client.jinja
openvpn/files/server.jinja

add support for missing crl-verify

add crl-verify support

---

openvpn/files/server.jinja
pillar.example

The management interface can be useful for gathering stats.

Allow configuring management interface

---

openvpn/config.sls
openvpn/files/client.jinja
openvpn/files/server.jinja
pillar.example

Add askpass option to client and server configs. This enables the password protection for the key file.

Add askpass option

---

openvpn/defaults.yaml
openvpn/map.jinja
openvpn/osfamilymap.yaml
openvpn/osmap.yaml

I want to add support for Windows to the formula, but before doing that I thought I would tidy up map.jinja, as there's a lot of duplication in there.

Consolidate map.jinja using split-out yaml files

---

openvpn/files/common_opts.jinja
openvpn/files/server.jinja

Move pkcs12 to common_opts

---

openvpn/config.sls
pillar.example

I have a need to place an OpenVPN configuration file outside the default directory.
This PR allows for this.

Allow non-default/config-specific config directory

---

openvpn/files/client.jinja
openvpn/files/common_opts.jinja
openvpn/files/server.jinja
openvpn/init.sls
pillar.example

please see commit-messages for details.

Various fixes and new config options

---

openvpn/files/common_opts.jinja
openvpn/files/server.jinja
pillar.example

Adding IPv6 support to openvpn, incorporating PR https://github.com/saltstack-formulas/openvpn-formula/pull/78 and https://github.com/saltstack-formulas/openvpn-formula/pull/80 into one request.

Ipv6 support

---

openvpn/config.sls
openvpn/files/ifconfig_pool_persist.jinja
openvpn/hardening.sls
openvpn/ifconfig_pool_persist.sls
openvpn/service.sls

Replate iteritems() with items() for python3

---

openvpn/config.sls
openvpn/files/client.jinja
openvpn/files/common_opts.jinja
openvpn/files/server.jinja

Tested on
- Ubuntu 18.04
- FreeBSD 11.2
This PR should fix #89.

Get rid of json_encode_dict; fixes #89

---

openvpn/network_manager_networks/files/connection.jinja

Reverts saltstack-formulas/openvpn-formula#95
Sry, I just found a bug, where I lost `service-type=org.freedesktop.NetworkManager.openvpn`, which in turn empties my VPN connection list.

Revert "NetworkManager: merge Pillar data"

---

openvpn/network_manager_networks/files/connection.jinja

fixed version of #95 
Tested on Ubuntu 16.04.5 (VPN is up and running as I write this.)
@aboe76 Sry for the inconvenience.

NetworkManager: merge Pillar data

---

openvpn/defaults.yaml
openvpn/service.sls
pillar.example

Hi,
I will control openvpn via PCS (Pacemaker+corosync). With this change, I can set openvpn:lookup:service_function: disabled and this formula will remove openvpn from autostart without stopping it.
Regards
Pascal

create value to control service function

---

openvpn/files/common_opts.jinja
openvpn/files/server.jinja

fix(config): script-security is a common option

---

pillar.example

This avoids Salt's yaml/json casting to bool.

Update example pillar with quoted "yes" for comp-lzo

---

openvpn/files/server.jinja
pillar.example

Server config can now have auth-gen-token, which is kinda required for OTP
authentications.

feat(auth_gen_token): support for auth-gen-token

---

.travis.yml
openvpn/repo.sls

* Semi-automated using https://github.com/myii/ssf-formula/pull/38
---
Based on discussions in #119.

fix(repo): provide EPEL repo configuration for `Amazon Linux-2`

---

openvpn/service.sls

fix(service): stop old service only if name is different to new service

---

openvpn/files/client.jinja

This fixes an embarrassing typo in #125, causing the `auth_nocache`
setting not to work at all.
---
No.

fix(auth_nocache): Fix typo in client template

---

test/integration/default/controls/config_spec.rb
test/salt/pillar/default.sls

---
Following #126 adding a test for this option.
No.
PR #126

test: add test for auth-nocache option

---

kitchen.github.yml
kitchen.vagrant.yml

---
No.
saltstack/salt#57628
A fix to the test setup for `v3001`, due to a Salt bug causing Kitchen `init_environment` to return a failing exit code.
NA
https://github.com/dafyddj/openvpn-formula/runs/797372874?check_suite_focus=true#step:8:29

ci: avoid `init_environment` failing due to saltstack/salt#57628

---

openvpn/_mapdata/_mapdata.jinja
openvpn/_mapdata/init.sls
test/integration/default/controls/_mapdata_spec.rb
test/integration/default/files/_mapdata/amazonlinux-1.yaml
test/integration/default/files/_mapdata/amazonlinux-2.yaml
test/integration/default/files/_mapdata/arch-base-latest.yaml
test/integration/default/files/_mapdata/centos-6.yaml
test/integration/default/files/_mapdata/centos-7.yaml
test/integration/default/files/_mapdata/centos-8.yaml
test/integration/default/files/_mapdata/debian-10.yaml
test/integration/default/files/_mapdata/debian-9.yaml
test/integration/default/files/_mapdata/fedora-31.yaml
test/integration/default/files/_mapdata/fedora-32.yaml
test/integration/default/files/_mapdata/fedora-33.yaml
test/integration/default/files/_mapdata/gentoo-2-sysd.yaml
test/integration/default/files/_mapdata/gentoo-2-sysv.yaml
test/integration/default/files/_mapdata/opensuse-15.yaml
test/integration/default/files/_mapdata/oraclelinux-7.yaml
test/integration/default/files/_mapdata/oraclelinux-8.yaml
test/integration/default/files/_mapdata/ubuntu-16.yaml
test/integration/default/files/_mapdata/ubuntu-18.yaml
test/integration/default/files/_mapdata/ubuntu-20.yaml
test/integration/default/files/_mapdata/windows-2019-server.yaml
test/integration/default/files/_mapdata/windows-8.yaml

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/284

refactor(map): use top-level `values:` key in `map.jinja` dumps

---

openvpn/_mapdata/init.sls
test/integration/default/files/_mapdata/amazonlinux-1.yaml
test/integration/default/files/_mapdata/amazonlinux-2.yaml
test/integration/default/files/_mapdata/arch-base-latest.yaml
test/integration/default/files/_mapdata/centos-6.yaml
test/integration/default/files/_mapdata/centos-7.yaml
test/integration/default/files/_mapdata/centos-8.yaml
test/integration/default/files/_mapdata/debian-10.yaml
test/integration/default/files/_mapdata/debian-9.yaml
test/integration/default/files/_mapdata/fedora-31.yaml
test/integration/default/files/_mapdata/fedora-32.yaml
test/integration/default/files/_mapdata/fedora-33.yaml
test/integration/default/files/_mapdata/gentoo-2-sysd.yaml
test/integration/default/files/_mapdata/gentoo-2-sysv.yaml
test/integration/default/files/_mapdata/opensuse-15.yaml
test/integration/default/files/_mapdata/oraclelinux-7.yaml
test/integration/default/files/_mapdata/oraclelinux-8.yaml
test/integration/default/files/_mapdata/ubuntu-16.yaml
test/integration/default/files/_mapdata/ubuntu-18.yaml
test/integration/default/files/_mapdata/ubuntu-20.yaml
test/integration/default/files/_mapdata/windows-2019-server.yaml
test/integration/default/files/_mapdata/windows-8.yaml

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/287

fix(_mapdata): ensure map data is directly under `values`

---

.gitlab-ci.yml
.travis.yml
kitchen.yml
test/integration/default/controls/services_spec.rb
test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml
test/integration/share/README.md
test/integration/share/libraries/system.rb

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/288

ci(kitchen+gitlab): update for new pre-salted images

---

.github/workflows/kitchen.yml
Gemfile
Gemfile.lock
kitchen.github.yml
kitchen.vagrant.yml

---
No.
Avoid Ruby gem dependency issues by installing and using the Chef packaged ruby, as this is the 
recommended practice on Windows [chef/chef#1535](https://github.com/chef/chef/issues/1535#issuecomment-46897676)

ci(kitchen): improve Windows testing

---

docs/README.rst

docs(readme): generalise Vagrant section to include `*BSD` [skip ci]

---

openvpn/parameters/map_jinja.yaml
openvpn/parameters/oscodename/openSUSE Tumbleweed.yaml
test/integration/default/files/_mapdata/amazonlinux-1.yaml
test/integration/default/files/_mapdata/amazonlinux-2.yaml
test/integration/default/files/_mapdata/arch-base-latest.yaml
test/integration/default/files/_mapdata/centos-6.yaml
test/integration/default/files/_mapdata/centos-7.yaml
test/integration/default/files/_mapdata/centos-8.yaml
test/integration/default/files/_mapdata/debian-10.yaml
test/integration/default/files/_mapdata/debian-9.yaml
test/integration/default/files/_mapdata/fedora-31.yaml
test/integration/default/files/_mapdata/fedora-32.yaml
test/integration/default/files/_mapdata/fedora-33.yaml
test/integration/default/files/_mapdata/gentoo-2-sysd.yaml
test/integration/default/files/_mapdata/gentoo-2-sysv.yaml
test/integration/default/files/_mapdata/opensuse-15.yaml
test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml
test/integration/default/files/_mapdata/oraclelinux-7.yaml
test/integration/default/files/_mapdata/oraclelinux-8.yaml
test/integration/default/files/_mapdata/ubuntu-16.yaml
test/integration/default/files/_mapdata/ubuntu-18.yaml
test/integration/default/files/_mapdata/ubuntu-20.yaml
test/integration/default/files/_mapdata/windows-10.yaml
test/integration/default/files/_mapdata/windows-2016-server.yaml
test/integration/default/files/_mapdata/windows-2019-server.yaml
test/integration/default/files/_mapdata/windows-8.yaml

---
No.
Avoid this failure:
```
ID: openvpn_create_dh_512
Function: cmd.run
Name: "openssl" dhparam -out "/etc/openvpn/dh512.pem" 512
Result: False
Comment: Command ""openssl" dhparam -out "/etc/openvpn/dh512.pem" 512" run
...
stderr:
/bin/bash: line 1: openssl: command not found
```

fix(tumbleweed): ensure `openssl` package is also installed
